baseurl = "https://consulate.scot/"
title = "Scottish Consulate"
languageCode = "en-gb"
defaultContentLanguage = "en"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
# googleAnalytics = ""

[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  copyright = "ⓒⓞⓟⓨⓡⓘⓖⓗⓣ ⓢⓒⓞⓣⓣⓘⓢⓗ ⓒⓞⓝⓢⓤⓛⓐⓣⓔ ②⓪①⑨ :scot_gary:"
  
  thelicense = "Except where otherwise noted, content on this website is licensed under the following license"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2
  [[languages.en.menu.main]]
    url = "/forms/"
    name = "Services"
    weight = 3
  [[languages.en.menu.main]]
    url = "/join/"
    name = "Join Us"
    weight = 4
  [[languages.en.menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 5
  [[languages.en.menu.main]]
    url = "https://scottishconsulate.org/"
    name = "Wiki"
    weight = 6

#[languages.de]
#  languageName = "Deutsch"
#
#  # Replace the default footer message with a localized message
#  copyright = "ⓤrheberrecht ⓢcottish ⓒonsulate ②019"
#
#  thelicense = "Sofern nicht anders angegeben, wird der Inhalt dieser Website unter der folgenden Lizenz lizenziert"
#
#  [[languages.de.menu.main]]
#    url = "/de/"
#    name = "Start"
#    weight = 1
#  [[languages.de.menu.main]]
#    url = "/about/"
#    name = "Über uns"
#    weight = 2
#  [[languages.de.menu.main]]
#    url = "/contact/"
#    name = "Kontakt"
#    weight = 3

# Links format

[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Consular Staff"

  # Date format (default: Jan 2, 2006)
  date_format = "Jan 2, 2006"

  # Display post summaries instead of content in list templates (default: true)
  truncate = false

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    # showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5

  [params.header]
    # Color scheme for the header (default: "light")
    # colorScheme = "dark"

  [params.footer]
    # Color scheme for the footer (default: "light")
    # colorScheme = "dark"
